In [1]:
import numpy as np
import math
import sklearn.metrics

In [2]:
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0001 ):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * 2 * eij * Q[k][j]
                        Q[k][j] = Q[k][j] + alpha * 2 * eij * P[i][k]
    return P, Q.T
R = [[0,5,4,2, 1],[1,0,0,5, 3], [1,4,4,1, 0],[0,0,2, 0, 2],[3,1,1,0, 0] ]
R = np.array(R)
N = len(R)
M = len(R[0])
K=1
P = np.random.rand(N,K)
Q = np.random.rand(M,K)
nP, nQ = matrix_factorization(R, P, Q, K)
nR = np.dot(nP, nQ.T)
print(nR)
print("Roll Num: CB.SC.I5DAS21049")
print("Name: Pratiksha Cauvery K P")

[[0.92301189 4.63211906 3.94497766 2.4115929  1.68875115]
 [1.63799278 8.22023821 7.00082526 4.27965427 2.99688685]
 [0.79991239 4.01434639 3.4188471  2.08996555 1.46352716]
 [0.57937176 2.90756709 2.47625051 1.51374955 1.06002397]
 [0.28230661 1.41675078 1.20658604 0.73759463 0.5165108 ]]
Roll Num: CB.SC.I5DAS21049
Name: Pratiksha Cauvery K P
